### ISSUE TITLE
invalid_issuer should return a 400(ish)

### ISSUE THREAD

**Issue by deybhayden** [grahac/alexa_request_verifier#1]
Hey @grahac - great work on this! I was just setting out to do this work today, and found you had done it for me 😅 . Readme is great, got me setup - just one quick note - I think that an invalid cert should return a 400 or 401 when supplied vs just erroring out.

```
11:58:22.608 request_id=74k2kqhqf56gte1d4ss2g8ciidbaed2o [debug] alexa_request_verifier: got error -  invalid_issuer
11:58:22.628 [error] #PID<0.2943.0> running Foo.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /alexa
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: nil
        (alexa_request_verifier) lib/alexa_request_verifier.ex:262: AlexaRequestVerifier.verify_signature/1
        (alexa_request_verifier) lib/alexa_request_verifier.ex:58: AlexaRequestVerifier.call/2
        ...
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

The lib does that when a signature didn't match, and it's a better experience:

```
11:59:40.306 request_id=5qqikip3u8vghiu3cviimo5cubaiah9b [info] POST /alexa
11:59:40.769 request_id=5qqikip3u8vghiu3cviimo5cubaiah9b [debug] alexa_request_verifier: setting cache for https://s3.amazonaws.com/echo.api/echo-api-cert-4.pem
11:59:40.769 request_id=5qqikip3u8vghiu3cviimo5cubaiah9b [debug] alexa_request_verifier: signature did not match
```

Overall though, super library!

**Comment by grahac** [comment]
Awesome. Thanks for noticing this.   I think I have a fix this but do not know for sure as I am having a hard time reproducing it.  Do you have a copy of the request you used that caused this? Would like to add it to the tests (or at least test it if it is sensitive).

Let me know!

**Comment by deybhayden** [comment]
Sure, I was passing an invalid cert in the header via curl:

```
$>  curl -i -X POST -d @launch.txt -H "Content-Type: application/json" -H "SignatureCertChainUrl: https://s3.amazonaws.com/echo.api/echo-api-cert.pem" -H "Signature: M4Xq8WmUHjaR4Fgj9HUheoOUkZf4tkc5koBtkBq/nCmh4X6EiimBXWa7p+kHoMx9noTdytGSUREaxYofTne1CzYOW0wxb9x6Jhor6lMwHAr4cY+aR1AEOkWrjsP94bewRr1/CxYNl7kGcj4+QjbEa/7dL19BNmLiufMLZDdRFsZSzlfXpPaAspsoStqVc/qc26tj5R9wtB0sTS4wbFc4eyCPFaCZocq1gmjfR3YQXupuD7J3slrz54SxukNmL/M1CIoZ8lOXjS82XLkKjsrzXdY5ePk8XsEDjNWkFSLbqzBzGBqzWx4M913uDA6gPx5tFKeoP8FgpV+BHKDf3d4gmQ==" http://localhost:4000/alexa
```

[launch.txt](https://github.com/grahac/alexa_request_verifier/files/980068/launch.txt)

**Comment by grahac** [comment]
Thanks. I believe this should now be fixed and uploaded to hex.  Let me know if it is still causing you issues.

**Comment by deybhayden** [comment]
Looks great, thanks @grahac (ps might want to update the version in the readme?)

**Comment by grahac** [comment]
Ah. Thanks for catching that.  Updated!  


On Wed, May 10, 2017 3:40 PM, Ben Hayden notifications@github.com  wrote:
Looks great, thanks @grahac  (ps might want to update the version in the
readme?)
