### ISSUE TITLE
Fix upgrade path for 1.3.0

### ISSUE THREAD

**Issue by spunkedy** [grahac/alexa_request_verifier#2]
when trying to use in a 1.3 phoenix project I get this. 

```Failed to use "phoenix" (version 1.3.0) because
  alexa_request_verifier (versions 0.1.3 and 0.1.4) requires ~> 1.2.3
```

**Comment by grahac** [comment]
Thanks Ed, for noticing this and updating with a pull request.  Accepted and merged. I also added a new version and updated hex.  One Q: I saw you added :inets as an external app.  Any particular reason? Probably better to have it as a separate app but I was wondering if there was a restriction/change in Phoenix 1.3 that caused you to make the addition.

**Comment by spunkedy** [comment]
Yeah, the :httpc calls weren't working without it for some reason, chased it down to needing that. 

Thanks for the merge!

**Comment by grahac** [comment]
Cool.  Thx for letting me know!
